# Generated by Django 5.1.4 on 2026-04-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditentry_is_archived'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditentry',
            new_name='audit_log_event_t_e775dd_idx',
            old_name='audit_log_event_t_idx',
        ),
        migrations.RenameIndex(
            model_name='auditentry',
            new_name='audit_log_user_id_3b54b4_idx',
            old_name='audit_log_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditentry',
            new_name='audit_log_target__775c76_idx',
            old_name='audit_log_target__idx',
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('session_timeout', 'Session Timeout'), ('create', 'Create'), ('update', 'Update'), ('key_field_change', 'Key Field Change'), ('export', 'Export'), ('consent_granted', 'Consent Granted'), ('consent_revoked', 'Consent Revoked'), ('break_glass', 'Break Glass'), ('break_glass_review', 'Break Glass Review'), ('approval', 'Approval'), ('media_upload', 'Media Upload'), ('media_dispute', 'Media Dispute'), ('infringement_report', 'Infringement Report'), ('payment_posted', 'Payment Posted'), ('refund_processed', 'Refund Processed'), ('sudo_mode_enter', 'Sudo Mode Enter'), ('sudo_mode_action', 'Sudo Mode Action'), ('user_disabled', 'User Disabled'), ('workstation_blacklisted', 'Workstation Blacklisted'), ('workstation_unblocked', 'Workstation Unblocked'), ('bulk_export', 'Bulk Export'), ('log_purge', 'Log Purge'), ('report_generated', 'Report Generated'), ('report_delivered', 'Report Delivered'), ('password_change', 'Password Change'), ('auth_login', 'Auth Login'), ('auth_logout', 'Auth Logout'), ('auth_password_change', 'Auth Password Change'), ('auth_sudo_acquire', 'Auth Sudo Acquire'), ('auth_sudo_release', 'Auth Sudo Release'), ('session_refresh', 'Session Refresh'), ('remember_device', 'Remember Device'), ('mpi_patient_search', 'Patient Search'), ('mpi_patient_create', 'Patient Create'), ('mpi_patient_view', 'Patient View'), ('mpi_patient_update', 'Patient Update'), ('mpi_break_glass', 'Break Glass Access'), ('consent_list', 'Consent List'), ('consent_create', 'Consent Create'), ('consent_view', 'Consent View'), ('consent_revoke', 'Consent Revoke'), ('media_download', 'Media Download'), ('media_watermark', 'Media Watermark'), ('media_repost_authorize', 'Media Repost Authorize'), ('media_infringement_create', 'Infringement Create'), ('media_infringement_update', 'Infringement Update'), ('financial_order_list', 'Order List'), ('financial_order_create', 'Order Create'), ('financial_order_view', 'Order View'), ('financial_order_void', 'Order Void'), ('financial_payment_create', 'Payment Create'), ('financial_refund_list', 'Refund List'), ('financial_refund_create', 'Refund Create'), ('financial_refund_approve', 'Refund Approve'), ('financial_refund_process', 'Refund Process'), ('financial_reconciliation_list', 'Reconciliation List'), ('financial_reconciliation_view', 'Reconciliation View'), ('financial_reconciliation_download', 'Reconciliation Download'), ('financial_auto_close', 'Auto-Close Unpaid Order'), ('financial_reconciliation_generated', 'Reconciliation Generated'), ('media_detail_view', 'Media Detail View'), ('media_list_view', 'Media List View'), ('report_download', 'Report Download'), ('report_dashboard_view', 'Report Dashboard View'), ('outbox_list_view', 'Outbox List View'), ('outbox_detail_view', 'Outbox Detail View'), ('media_attach_patient', 'Media Attach Patient'), ('user_create', 'User Create'), ('user_update', 'User Update'), ('user_disable', 'User Disable'), ('user_enable', 'User Enable'), ('workstation_unblock', 'Workstation Unblock')], db_index=True, max_length=50),
        ),
    ]
